# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
      $a = 5 
      $b = 10 
      $c = $a + $b 
      If ($c -gt 10)
      {
        Write-Host "Sum of $a, $b is greater than 10"
      }
      Else 
      {
         Write-Host "Sum of $a, $b is less than 10" 
      }
      $i = 0 
      while ($i -lt 10)
      {
        $i++
        If ($i -lt $b)
          Write-Host $i less than $b
        else
          Write-Host $i greater than $b   
      }